test-19

diff --git a/.github/workflows/generate_openapi.yml b/.github/workflows/generate_openapi.yml
--- a/.github/workflows/generate_openapi.yml
+++ b/.github/workflows/generate_openapi.yml
@@ -33,12 +33,19 @@ jobs:
       - name: Check for Changes in openapi.json
         id: check_changes
         run: |
-          git diff --exit-code -- openapi.json || echo "Changes detected in openapi.json"
+          if [[ $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}) == *"openapi.json"* ]]; then
+            echo "Changes detected in openapi.json"
+            exit 0
+          else
+            echo "No changes detected in openapi.json"
+            exit 1  # Exit with a non-zero code to indicate no changes
+          fi
 
       - name: Commit and Push Changes
+        if: steps.check_changes.outputs.return-code == '0'
         run: |
           git config user.name "${{ github.actor }}"
           git config user.email "${{ github.actor }}@users.noreply.github.com"
           git add openapi.json
           git commit -m "Update OpenAPI"
-          git push origin ${{ github.head_ref }}
+          git push origin HEAD:${{ github.head_ref }}
